/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Vinicio
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    Graph Graph = new Graph();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nodeAddDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nodeAddName = new javax.swing.JTextField();
        nodeAddType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nodeAddNodeA = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nodeAddLength = new javax.swing.JSpinner();
        nodeAddBandWidth = new javax.swing.JSpinner();
        coaxial = new javax.swing.JRadioButton();
        fiber = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nodeUpdateDialog = new javax.swing.JDialog();
        nodeDeleteDialog = new javax.swing.JDialog();
        bG = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jLabel1.setText("Nombre (Código)");

        jLabel2.setText("Punto de Nodo");

        nodeAddType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Repetidor de Red Doméstica", "Repetidor de Red Empresarial", "Antena Celular", "Conexión Dedicada" }));

        jLabel3.setText("Nodo Adjunto");

        jLabel4.setText("Distancia (m)");

        jLabel5.setText("Ancho de Banda (MB/s)");

        nodeAddLength.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        nodeAddBandWidth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        bG.add(coaxial);
        coaxial.setSelected(true);
        coaxial.setText("Cable Coaxial");
        coaxial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coaxialActionPerformed(evt);
            }
        });

        bG.add(fiber);
        fiber.setText("Fibra Optica");
        fiber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiberActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo de Conexión");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nodeAddDialogLayout = new javax.swing.GroupLayout(nodeAddDialog.getContentPane());
        nodeAddDialog.getContentPane().setLayout(nodeAddDialogLayout);
        nodeAddDialogLayout.setHorizontalGroup(
            nodeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nodeAddDialogLayout.createSequentialGroup()
                .addGroup(nodeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nodeAddDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(nodeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nodeAddDialogLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nodeAddBandWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(nodeAddDialogLayout.createSequentialGroup()
                                .addGroup(nodeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(99, 99, 99)
                                .addGroup(nodeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(nodeAddDialogLayout.createSequentialGroup()
                                        .addComponent(coaxial)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fiber))
                                    .addComponent(nodeAddNodeA, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nodeAddName)
                                    .addComponent(nodeAddType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nodeAddLength, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(nodeAddDialogLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nodeAddDialogLayout.setVerticalGroup(
            nodeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nodeAddDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nodeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nodeAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nodeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(nodeAddType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nodeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(nodeAddNodeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nodeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nodeAddLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nodeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coaxial)
                    .addComponent(fiber)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nodeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nodeAddBandWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout nodeUpdateDialogLayout = new javax.swing.GroupLayout(nodeUpdateDialog.getContentPane());
        nodeUpdateDialog.getContentPane().setLayout(nodeUpdateDialogLayout);
        nodeUpdateDialogLayout.setHorizontalGroup(
            nodeUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        nodeUpdateDialogLayout.setVerticalGroup(
            nodeUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout nodeDeleteDialogLayout = new javax.swing.GroupLayout(nodeDeleteDialog.getContentPane());
        nodeDeleteDialog.getContentPane().setLayout(nodeDeleteDialogLayout);
        nodeDeleteDialogLayout.setHorizontalGroup(
            nodeDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        nodeDeleteDialogLayout.setVerticalGroup(
            nodeDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TOGO Mapper");
        setResizable(false);

        jMenu1.setText("Nodo");

        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Editar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Eliminar");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.nodeAddNodeA.setModel(new DefaultComboBoxModel());
        for (Vertex vertex : Graph.getVertex()) {
            this.nodeAddNodeA.addItem(vertex.getName() + ", " + vertex.getType());
        }
        this.nodeAddDialog.pack();
        this.nodeAddDialog.setModal(true);
        this.nodeAddDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void coaxialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coaxialActionPerformed
        if (this.coaxial.isSelected() && !this.fiber.isSelected()) {
            this.nodeAddBandWidth.setModel(new SpinnerNumberModel(1.0, 1.0, 100.0, 1.0));
        } else {
            this.nodeAddBandWidth.setModel(new SpinnerNumberModel(1.0, 1.0, 10240.0, 1.0));
        }
    }//GEN-LAST:event_coaxialActionPerformed

    private void fiberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiberActionPerformed
        if (this.coaxial.isSelected() && !this.fiber.isSelected()) {
            this.nodeAddBandWidth.setModel(new SpinnerNumberModel(1.0, 1.0, 100.0, 1.0));
        } else {
            this.nodeAddBandWidth.setModel(new SpinnerNumberModel(1.0, 1.0, 10240.0, 1.0));
        }
    }//GEN-LAST:event_fiberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.nodeAddName.getText().equals("")) {
            JOptionPane.showMessageDialog(this.nodeAddDialog, "No ha ingresado un Número", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
        } else {
            this.Graph.addNode(new Vertex(this.nodeAddName.getText(), this.nodeAddType.getSelectedItem().toString()));
            System.out.println(this.nodeAddBandWidth.getValue().toString());
            this.Graph.addEdge(new Edge(Integer.parseInt(this.nodeAddLength.getValue().toString()), Integer.parseInt(this.nodeAddBandWidth.getValue().toString()), this.Graph.getVertex()[this.nodeAddNodeA.getSelectedIndex()], this.Graph.getVertex()[this.Graph.getVertex().length - 1]));
            this.nodeAddName.setText("");
            this.nodeAddType.setSelectedIndex(0);
            this.nodeAddNodeA.setSelectedIndex(0);
            this.nodeAddLength.setValue(1);
            this.coaxial.setSelected(true);
            this.nodeAddBandWidth.setValue(1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bG;
    private javax.swing.JRadioButton coaxial;
    private javax.swing.JRadioButton fiber;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JSpinner nodeAddBandWidth;
    private javax.swing.JDialog nodeAddDialog;
    private javax.swing.JSpinner nodeAddLength;
    private javax.swing.JTextField nodeAddName;
    private javax.swing.JComboBox<String> nodeAddNodeA;
    private javax.swing.JComboBox<String> nodeAddType;
    private javax.swing.JDialog nodeDeleteDialog;
    private javax.swing.JDialog nodeUpdateDialog;
    // End of variables declaration//GEN-END:variables
}
